import {Ingredient} from './models';


export const INGREDIENTS: Ingredient[] = [
  {
    id: 1,
    ing1: 'ground meat (beef, pork, or both), at least 20% fat',
    amount1: '500 g',
    ing2: 'small onion',
    amount2: '1',
    ing3: 'cauliflower rice',
    amount3: '350 g',
    ing4: 'lemons',
    amount4: '2',
    ing5: 'eggs',
    amount5: '3',
    ing6: 'butter',
    amount6: '50 g',
    ing7: 'garlic',
    amount7: '1 clove',
    ing8: 'concentrated chicken or vegetable stock',
    amount8: '2 tsp',
    ing9: '',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Saute the cauliflower rice with no (or very little) oil and stir frequently, until it dries up, making sure it doesn\'t stick.\\n(Note that this picture only has half the amount of cauliflower rice the recipe needs)\\n![The cauliflower rice, after it\'s cooked enough to dry',
    step2: 'In a large pot, add 1.5 liters of water, the butter, 2 tbsp olive oil, and the chicken stock and bring to the boil. While you\'re waiting for it to boil, make the meatballs.',
    step3: 'In a large bowl, mix well:\\n- the ground meat\\n- the white from 1 egg (save the yolk for the avgolemono)\\n- the parsley and dill (if using dried, about 1 tbsp each, adjust accordingly for fresh (which is preferable)\\n- The onion\\n- 3 tbsp olive oil\\n- 2 tsp salt\\n- Some pepper\\n\\nMix it very well and once it\'s thoroughly mixed, add 100 g of the cauliflower rice.\\n![The ground meat mix',
    step4: 'Make small balls with the meatball mix, around 30-40, the smaller the tastier. I made 32, so aim for even smaller than this.\\n!',
    step5: 'Lower the meatballs one by one slowly into the boiling water. Put the lid on, and simmer for 30-35 minutes in medium to low heat.\\n!',
    step6: 'After 20-25 minutes (so 10 minutes before they are done) take a cup of liquid out, and add the remaining cauliflower rice to the pot.',
    step7: 'Beat the 2 eggs and remaining yolk with the juice of the two lemons and when they are homogenized well, start very slowly pouring the cup of stock into the mixture, a little at a time, while beating the mixture with a whisk (ideally an electric whisk). **This needs patience. ** If you don\'t do this slowly enough, the avgolemono will fail. You need to maintain a homogeneous consistency as you whisk. Doing it too fast will cook the egg and you\'ll have disgusting cooked bits of egg white floating in your avgolemono (there is even an expression for this in Greek, \\"?? ?????????? ?????\\',
    step8: 'Once the meatballs have been cooking for 30 minutes, pour the avgolemono in the pot and stir very well. Bring to a boil once more, stirring frequently.\\n!',
    step9: '**That\'s it!** Serve in bowls, with plenty of liquid. This dish can have a range of consistencies and they\'re all ok: with a thicker liquid, it\'s more of a sauce, whereas thinner liquid (like in the picture), is more like soup. Up to you!',
    step10: ''
  },
  {
    id: 2,
    ing1: 'tahini',
    amount1: '0.5 cup',
    ing2: 'eggs',
    amount2: '4',
    ing3: 'baking powder',
    amount3: '1 tsp',
    ing4: 'honey',
    amount4: '30 g',
    ing5: 'eggs',
    amount5: '3',
    ing6: 'butter',
    amount6: '3 tbsp',
    ing7: 'maple extract',
    amount7: '1 tsp',
    ing8: 'cinammon',
    amount8: '1 tsp',
    ing9: '',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Beat all ingredients together really well in a blender.',
    step2: 'Pour mixture in an oiled cake tray (we suggest sesame oil for the oiling) and sprinkle with sesame seeds.',
    step3: 'Bake for 25-30 minutes at 345F (convection bake is better). Depending on your oven, you may want to turn it around (horizontally) after 15 minutes to ensure even baking.',
    step4: 'Done, enjoy! We actually eat it with a spoon straight from the cake tray!',
    step5: '',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 3,
    ing1: 'heavy cream',
    amount1: '4 cups',
    ing2: 'icing sugar or substitite',
    amount2: '1 cup',
    ing3: 'egg yolks',
    amount3: '4',
    ing4: 'Grand Marnier',
    amount4: '0.25 cup',
    ing5: 'espresso',
    amount5: '1 shot',
    ing6: 'vanilla extract',
    amount6: '1 tbsp',
    ing7: 'Cocoa nibs for garnish',
    amount7: '',
    ing8: '',
    amount8: '',
    ing9: '',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Beat the heavy cream with half of the icing sugar substitute (added slowly) until starting to get thick',
    step2: 'Beat the egg yolks with the remaining half of the icing sugar substitute.',
    step3: 'Whisk the Grand Marnier, coffee, vanilla extract into the egg yolk mixture.',
    step4: 'Whisk the egg yolk mixture into the heavy cream mixture',
    step5: 'Done! Add to your ice cream machine per manufacturer\'s instructions or freeze and stir every 30 minutes or so.',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 4,
    ing1: 'turnip noodles',
    amount1: '16 oz',
    ing2: 'rashers bacon',
    amount2: '6',
    ing3: 'eggs',
    amount3: '6',
    ing4: 'parmesan',
    amount4: '0.5 cup',
    ing5: 'cloves garlic',
    amount5: '4',
    ing6: 'heavy cream',
    amount6: '0.25 cup',
    ing7: 'Salt',
    amount7: '',
    ing8: 'Pepper',
    amount8: '',
    ing9: '',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Cut the bacon into lardons and saute until it\'s lightly cooked.',
    step2: 'hile the bacon is cooking, separate the yolks from 4 of the eggs. Whisk the 4 yolks, 2 whole eggs, the grated parmesan, the cream, and salt and pepper.',
    step3: 'If using garlic, add it once the bacon is starting to get cooked and saute for a few more minutes until fragrant',
    step4: 'Stir in turnip noodles until they are cooked through to desired doneness',
    step5: 'Turn the heat down to very low and stir in the egg mixture. Stir rapidly until it cooks, remove from heat.',
    step6: 'Top with a little more ground pepper and serve!',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 5,
    ing1: 'lamb chops',
    amount1: '8',
    ing2: 'olive oil',
    amount2: '0.25 cup',
    ing3: 'garlic cloves',
    amount3: '4',
    ing4: 'medium ripe mango',
    amount4: '1',
    ing5: 'fresh mint',
    amount5: '1 cup',
    ing6: 'green onions',
    amount6: '2',
    ing7: 'fresh lime juice',
    amount7: '1 tbsp',
    ing8: 'serrano chile',
    amount8: '1',
    ing9: 'ripe avocado',
    amount9: '0.5',
    ing10: 'ground coriander',
    amount10: '2 tsp',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'In a blender or mini food processor, blend all the sauce ingredients, and chill in the fridge.',
    step2: 'Blend the olive oil and garlic and coat the lamb chops.',
    step3: 'Make the spice mix, and coat the lamb chops well on both sides.',
    step4: 'Grill the lamb chops on a very hot cast iron grill pan (or a BBQ if you have one!) for 2-3 minutes on each side for medium rare.',
    step5: 'Done! Serve with the sauce on the side.',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 6,
    ing1: 'eggplants',
    amount1: '3',
    ing2: 'thyme, salt, black pepper',
    amount2: '',
    ing3: 'beef or lamb',
    amount3: '2 lbs',
    ing4: 'yellow onions',
    amount4: '2',
    ing5: 'garlic cloves',
    amount5: '6',
    ing6: 'passata (Italian-style sieved tomato puree)',
    amount6: '500 g',
    ing7: 'cinammon, cloves and allspice',
    amount7: '',
    ing8: 'Better than Bouillon or other beef bouillon base',
    amount8: '4 tsp',
    ing9: 'Metaxa or other cognac',
    amount9: '0.5 cup',
    ing10: 'Sukrin Gold or brown sugar',
    amount10: '2 tbsp',
    ing11: 'Worcestershire sauce',
    amount11: '',
    ing12: 'butter',
    amount12: '1 cup',
    ing13: 'coconut flour',
    amount13: '0.5 cup',
    ing14: 'egg yolks',
    amount14: '4',
    ing15: 'hard cheese (we used Gruyere)',
    amount15: '250 g',
    step1: 'Cut the eggplants in half and scoop out the center. Leave about 1-1.5cm of flesh. Carve the flesh crosswise.',
    step2: 'Season the eggplants well with olive oil, salt, pepper, thyme. Use your hands to make sure it goes everywhere. Be fast, because they absorb the oil very quickly!',
    step3: 'Put eggplants on a large baking tray, cut side down and bake at 200C (392F) for 30-40 minutes.',
    step4: 'Fry the onions in the butter on high heat.\\n2. Once the onions have started to caramelize, add the garlic and fry for a few more minutes.\\n3. Add the cinnamon, cloves, allspice, black pepper and give it a stir.\\n4. Add the mince and bay leaves and reduce heat to medium.\\n5. Once the meat has started to brown, pour in the Metaxa.\\n6. Add the tomato puree, Sukrin Gold, bouillon base, and Worcestershire sauce and stir well.\\n5. Reduce heat and simmer for about half an hour or until the tomato tastes cooked and any liquids have been reduced.',
    step5: 'Melt the butter in a small pot over low heat\\n2. Whisk in the coconut flour, stirring continuously to make a roux\\n3. When the roux ingredients are nicely combined, whisk in the cream, adding a little each time to avoid lumps\\n4. Cook it over low heat, stirring continuously\\n5. When it has thickened, add nutmeg, salt, pepper to taste\\n6. Take it off the heat and stir in the yolks and grated cheese',
    step6: 'Scoop the minced meat into the eggplants, and top it with the bechamel. Bake for 10 minutes at 200C (392F), checking frequently because ovens vary. You may want to turn on the grill (US: broiler) for the last 5 minutes to give the cheese a nice golden brown.',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 7,
    ing1: 'shelled and deveined shrimp',
    amount1: '2 lbs',
    ing2: 'garlic',
    amount2: '1 head',
    ing3: 'extra-virgin olive oil',
    amount3: '1.25 cup',
    ing4: 'dried hot red chile',
    amount4: '1',
    ing5: 'dry sherry',
    amount5: '2 tbsp',
    ing6: 'lemon zest',
    amount6: '1 tsp',
    ing7: 'smoked paprika and salt',
    amount7: '',
    ing8: '',
    amount8: '',
    ing9: '',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'In a large bowl, toss the shrimp with 1 teaspoon of kosher salt and let stand for 10 minutes.',
    step2: 'Meanwhile, in a 9- to 10-inch enameled cast-iron skillet, combine the garlic and olive oil and cook over moderately low heat, stirring occasionally, until the garlic is very fragrant and just starts to brown, 8 to 10 minutes.',
    step3: 'Add the chile and smoked paprika and cook, stirring, until fragrant, 15 to 30 seconds',
    step4: 'Add the shrimp to the skillet and cook over medium heat, stirring and turning the shrimp occasionally, until barely pink, about 5 minutes',
    step5: 'Stir in the parsley, sherry, lemon zest and a generous pinch of salt. Remove from the heat and let stand until the shrimp are cooked through, 3 to 5 minutes. Serve in the skillet, passing crusty bread at the table.',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 8,
    ing1: 'Olive oil',
    amount1: '3 tbsp',
    ing2: 'Yellow onions',
    amount2: '2 medium',
    ing3: 'Miced lamb or beef',
    amount3: '1.5 lb',
    ing4: 'Organic green bell pepper',
    amount4: '1 large',
    ing5: 'Jalapeno chilli',
    amount5: '1',
    ing6: 'Garlic',
    amount6: '1 head',
    ing7: 'Tomato concentrate',
    amount7: '1 7 oz jar',
    ing8: 'Chopped peeled tomatoes',
    amount8: '1 28 oz tin',
    ing9: 'Red wine',
    amount9: '1 cup',
    ing10: 'Bay leaves',
    amount10: '4',
    ing11: 'Erythritol',
    amount11: '2 tbsp',
    ing12: 'Beef stock concentrate',
    amount12: '1 tbsp',
    ing13: 'Smoked Paprika',
    amount13: '1 tbsp',
    ing14: 'Cumin seed',
    amount14: '1 tbsp',
    ing15: 'Freerange eggs',
    amount15: '8',
    step1: 'Heat oil in a large, deep, preferably ceramic, frying pan on medium heat',
    step2: 'Cook onions until translucent, 5-10 min',
    step3: 'Add minced meat, stir until lightly browned',
    step4: 'Reduce heat a little, add jalapeno and bell pepper, cook until slightly soft. 3-4 min, do not overcook',
    step5: 'Add garlic and tomato concentrate, stir for 2 min until tomato tastes cooked not raw',
    step6: 'Add the wine. Tip: pour the wine into the tomato paste jar and shake it to get the last of the paste out.',
    step7: 'Add canned tomatoes, cumin, caraway seeds, bay leaves, paprika, erythritol, concentrated stock, and pepper. Yes, that is a lot of cumin; it will be fine. Bring to low boil, reduce heat, simmer for 20 min',
    step8: 'Place de-stemmed Swiss chard leaves on top of cooked tomato mixture. Make 8 small depressions with a spoon',
    step9: 'Crack one egg into each depression. Cover (a transparent lid is ideal)',
    step10: 'Cook until egg white is _just_ set. Serve immediately, in the pan.'
  },
  {
    id: 9,
    ing1: 'Garlic',
    amount1: '0.5 head',
    ing2: 'Anchovies',
    amount2: '5',
    ing3: 'Free-range egg yolks',
    amount3: '3',
    ing4: 'Dijon Mustard',
    amount4: '1 tsp',
    ing5: 'Worcestershire sauce',
    amount5: '1 good splash',
    ing6: 'Extra-virgin Greek olive oil',
    amount6: '1 cup',
    ing7: 'Parmesan',
    amount7: '0.5 cup',
    ing8: 'Black pepper',
    amount8: '',
    ing9: 'Lemon juice',
    amount9: '2 tbsp',
    ing10: 'Romaine hearts',
    amount10: '3',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Traditionally using a mortar and pestle (but a hand blender works just as well, we find) turn the garlic, anchovies and a pinch of salt into a fine paste.',
    step2: 'Add the whisked egg yolks, lemon juice, Worcestershire sauce and mustard. This can be done in a bowl with a whisk, or if using a blender continue with that.',
    step3: 'Gradually at first, add the oil and whisk/blend with each addition.',
    step4: 'Add the Parmesan and mix well.',
    step5: 'Taste, adjust with salt, pepper, lemon as desired.',
    step6: 'Either shred the romaine hearts and toss with the sauce, or serve individual leaves for dipping.',
    step7: 'f liked, garnish with more whole anchovies and/or Parmesan flakes',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 10,
    ing1: 'almond flour',
    amount1: '130 g',
    ing2: 'nutritional yeast',
    amount2: '40 g',
    ing3: 'mozarella',
    amount3: '330 g',
    ing4: 'eggs',
    amount4: '3',
    ing5: 'mascarpone',
    amount5: '4 tbsp',
    ing6: 'tomato concentrate/paste',
    amount6: '200 g',
    ing7: 'garlic',
    amount7: '5 cloves',
    ing8: 'dried basil (or 1 tbsp fresh)',
    amount8: '1 tsp',
    ing9: 'dry red wine',
    amount9: '1 splash',
    ing10: 'soy sauce',
    amount10: '1 splash',
    ing11: 'Worcestershire sauce ',
    amount11: '1 splash',
    ing12: 'Sukrin Gold ',
    amount12: '1 tsp',
    ing13: 'cheddar, gouda, gruyere or similar grated',
    amount13: '250 g',
    ing14: 'bacon',
    amount14: '5 oz',
    ing15: 'mushrooms',
    amount15: '6 oz',
    step1: 'Mix two thirds of the grated mozzarella, the almond flour, and the nutritional yeast in a microwaveable bowl. Add the mascarpone. Microwave on HIGH for 1 minute.',
    step2: 'Add cumin, garlic, salt, pepper. Stir then microwave on HIGH for another minute. Repeat until it\'s soft, usually doesn’t need more than 2 minutes total.',
    step3: 'Add the eggs and mix gently.',
    step4: 'Put a piece of parchment paper over your pizza stone, add the dough on top of it and then another piece of parchment paper. Use a rolling pin to roll it as close as possible to the pizza stone shape and evenly around 5mm thick or less. Remove the top sheet of parchment paper.',
    step5: 'Make fork holes all over the pizza base to ensure it cooks evenly. Bake at 215C/420F for 15 minutes or until golden brown.',
    step6: 'If you can manage to flip the pizza over without breaking it, flip it and bake a bit longer to make it crispy. If you’re worried it will break don\'t flip it, we never do and it’s fine!',
    step7: 'While the base is baking, make the tomato sauce: in a mini-blender of food processor blend the tomato paste, garlic wine, basil, Worcestershire sauce, oregano. Cook at medium-low heat for 5-10 minutes or until thickened a bit.',
    step8: 'While the base is baking and the sauce simmering, cut the bacon into 5mm lardons and saute with the mushrooms until almost (but not completely) cooked to your liking.',
    step9: 'Once the pizza base is done, spread the sauce over it as evenly as you can (a brush or rubber spatula helps). Then add the remaining grated cheeses, the bacon, the mushrooms, the pepper, the pineapple.',
    step10: 'Broil at 260C/500F for about 5 minutes, checking frequently because ovens vary. Enjoy!'
  },
  {
    id: 11,
    ing1: 'mushrooms',
    amount1: '10 oz',
    ing2: 'thick cut smoked bacon',
    amount2: '7 oz',
    ing3: 'green bell pepper',
    amount3: '1',
    ing4: 'garlic',
    amount4: '10 cloves',
    ing5: 'cheddar and heavy cream',
    amount5: '1 cup',
    ing6: 'whole nutmeg',
    amount6: '0.2',
    ing7: 'coconut oil',
    amount7: '1 tbsp',
    ing8: 'Thyme',
    amount8: '1 pinch',
    ing9: 'Worcestershire sauce',
    amount9: '',
    ing10: 'Salt, pepper',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Cut each strip of bacon into 4mm ',
    step2: 'Fry the bacon in the butter on medium-high heat until starting to turn translucent',
    step3: 'Add sliced mushrooms. Season with black pepper',
    step4: 'Continue to fry until mushrooms release their liquid and are turning darker. ',
    step5: 'In a separate pan, fry the pepper in the coconut oil until softened and just starting to turn brown.',
    step6: 'Add garlic to the mushrooms and stir until fragrant. Add thyme and stir. Then add a generous splash of Worcestershire sauce.',
    step7: 'Pour the cream into the mushrooms, bring to a low boil, then reduce heat.',
    step8: 'Add the green peppers',
    step9: 'When the cream reduces a bit, add the grated cheese and stir until melted.',
    step10: 'Grate the nutmeg into the mixture and serve.'
  },
  {
    id: 12,
    ing1: 'raw chicken liver',
    amount1: '500 g',
    ing2: 'large white onion',
    amount2: '1',
    ing3: 'garlic',
    amount3: '2 cloves',
    ing4: 'Metaxa or other brandy/cognac',
    amount4: '150 ml',
    ing5: 'heavy cream',
    amount5: '150 ml',
    ing6: 'Butter',
    amount6: '50 g',
    ing7: 'Salt, pepper',
    amount7: '',
    ing8: 'Parsley',
    amount8: '',
    ing9: 'balsamic reduction',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Chop most of the onion but set a little aside for garnish',
    step2: 'Saute garlic and onion in a bit of butter.  ',
    step3: 'Add the livers and saute on both sides until they have a bit color but are still pink inside. Season with salt and pepper.',
    step4: 'Add the Metaxa and let it steam away.',
    step5: 'Put all in a tall blender glass and add the cream and remaining butter and blend until smooth',
    step6: 'Put aside in fridge for at least 4 hours and serve, garnishing with the balsamic reduction, parsley and the onion from step 1.',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 13,
    ing1: 'whole raw octopus',
    amount1: '2',
    ing2: 'dry red cooking wine',
    amount2: '1 bottle',
    ing3: 'cloves',
    amount3: '6',
    ing4: 'bay leaves',
    amount4: '4',
    ing5: 'extra virgin olive oil',
    amount5: '',
    ing6: 'potato or turnip',
    amount6: '1 large',
    ing7: 'Kalamata olives',
    amount7: '0.5 cup',
    ing8: '',
    amount8: '',
    ing9: '',
    amount9: '',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Wash the octopus, remove the eyes and beak, and separate the tentacles. Cut each tentacle in 2-3 pieces of roughly equal volume, same for the head.',
    step2: 'Put tentacles and head in a large pot with nothing else and boil over medium heat.',
    step3: 'You will notice that the octopus is releasing juices and slowly become redder. As the juices start to evaporate, slowly pour in the wine.',
    step4: 'Once you\'ve poured all wine, add cloves and bay leaves.',
    step5: 'Simmer for about two hours. Half an hour before done, add the potatoes or turnips and the olives.',
    step6: 'Once it\'s reduced and the octopus and vegetables are tender add 1tbsp olive oil, mix, and serve! Makes about 6 portions.',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 14,
    ing1: 'half pound salmon fillets',
    amount1: '2',
    ing2: 'bean sprouts',
    amount2: '1 lbs',
    ing3: 'soy sauce',
    amount3: '0.25 cup',
    ing4: 'erythritol',
    amount4: '1 tbsp',
    ing5: 'fresh ginger',
    amount5: '1 tsp',
    ing6: 'garlic',
    amount6: '4 cloves',
    ing7: 'mirin or dry sherry',
    amount7: '2 tbsp',
    ing8: 'toasted sesame oil',
    amount8: '2 tsp',
    ing9: 'spring onion',
    amount9: '1',
    ing10: '',
    amount10: '',
    ing11: '',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'In a small saucepan over medium-high heat, combine the soy sauce, erythritol, ginger, garlic, mirin and sesame oil. Bring to a simmer, stirring until the erythritol has dissolved, about 1 minute. Let cool to room temperature. Reserve 1/4 cup (2 fl. oz./60 ml) of the sauce.',
    step2: 'Place the salmon fillets in separate zip lock bags and pour the remaining sauce into the bags, dividing evenly. If you have time you can let them marinate for 1-4 hours, but you don’t have to.',
    step3: 'Prepare a sous vide immersion circulator for use according to the manufacturer’s instructions. Preheat the water to 122°F (50°C). Place the bags into the circulating water and cook for 40 minutes for medium doneness.',
    step4: '5 minutes before the salmon is done, stir fry the bean sprouts in a large pan with a tsp of sesame oil and a splash of soy sauce. Divide evenly in two plates.',
    step5: 'Once the salmon is done, sear the skin in the same pan for 30 seconds. Place each fillet on top of the bean sprouts and pour the saved sauce on it. Optionally, you can also use the sauce from the ziplock bags, but keep in mind it will be more watery (we did anyway).',
    step6: 'Garnish with the sliced spring onion and serve!',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 15,
    ing1: 'eggs',
    amount1: '7',
    ing2: 'zucchini',
    amount2: '6',
    ing3: 'parsley',
    amount3: '0.5 bunch',
    ing4: 'dill',
    amount4: '0.5 bunch',
    ing5: 'dried mint',
    amount5: '1 tsp',
    ing6: 'graviera',
    amount6: '0.5 cup',
    ing7: 'feta',
    amount7: '0.5 cup',
    ing8: 'red onion',
    amount8: '1',
    ing9: 'spring onion',
    amount9: '1',
    ing10: 'olive oil',
    amount10: '',
    ing11: 'salt and pepper',
    amount11: '',
    ing12: '',
    amount12: '',
    ing13: '',
    amount13: '',
    ing14: '',
    amount14: '',
    ing15: '',
    amount15: '',
    step1: 'Add a lot of salt to the grated zucchini and squeeze well with a towel or cheesecloth to remove moisture.',
    step2: 'Beat the eggs in a bowl and set aside',
    step3: 'In a large bowl, mix the zucchini, parsley, dill, onion, spring onion, cheeses, pepper, eggs.',
    step4: 'Add the olive oil to the mix.',
    step5: 'Spread on a deep, oiled baking tray and bake at 180-200C (350-390F) for about 40 minutes or until golden.',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 16,
    ing1: 'almond flour',
    amount1: '1.5 cup',
    ing2: 'butter or ghee',
    amount2: '200 g',
    ing3: 'brown sugar substitute',
    amount3: '3 tbsp',
    ing4: 'vanilla extract',
    amount4: '4 tbsp',
    ing5: 'cinammon',
    amount5: '1 tsp',
    ing6: 'Salt',
    amount6: 'a pinch',
    ing7: 'Mascarpone',
    amount7: '40 oz',
    ing8: 'icing sugar substitute',
    amount8: '4 tbsp',
    ing9: 'lemon',
    amount9: '1',
    ing10: 'vanilla extract',
    amount10: '2 tbsp',
    ing11: 'strawberries or other berries',
    amount11: '1 lbs',
    ing12: 'gelatin',
    amount12: '0.5 scoop',
    ing13: 'lemon',
    amount13: '1',
    ing14: 'Sukrin Gold or similar',
    amount14: '2 tbsp',
    ing15: '',
    amount15: '',
    step1: 'In a medium frying pan, melt the ghee under low heat. \\n2. Add the almond and coconut flour and stir continuously. \\n3. It will look very runny at first, that\'s normal. When it starts darkening and becoming more viscous, add the cinnamon and sweetener. \\n4. When it\'s light brown and most of the the ghee has been absorbed, it\'s about done. At that point, add the vanilla extract. It will foam, that\'s ok. Stir until it goes down again.\\n5. Press into a 9\\" springform cake tray. Let it cool down in the fridge.',
    step2: 'With a mixer beat the mascarpone on its own for a bit, then add icing sugar substitute to taste, then the rest of the ingredients. Blend until even. If you want the cheesecake to be extra fluffy, just beat it longer. Make sure the ghee in the bottom layer has solidified, then spread over the base in the cake tray. Put it back in the fridge',
    step3: 'Blend half of the fruits and cut the other half into slices. Using a small pot, heat up the blended strawberries, Sukrin Gold, lemon juice and stir frequently until all heated up and mixed well. Add the gelatin slowly by sprinkling and stirring so that it doesn\'t clump. Then add the sliced fruits and stir. Simmer for a bit, then take it off the heat and let it cool down a bit. Once it starts getting viscous, spread it over the cream and put it back in the fridge.',
    step4: 'Chill in the fridge for at least 3 hours, then enjoy!',
    step5: '',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  },
  {
    id: 17,
    ing1: 'beef chuck',
    amount1: '2 pounds',
    ing2: 'shallots',
    amount2: '1 cup',
    ing3: 'unrefined coconut oil',
    amount3: '6 tbsp',
    ing4: 'soy sauce',
    amount4: '3 tbsp',
    ing5: 'beef broth',
    amount5: '9 cup',
    ing6: 'medium turnip',
    amount6: '1',
    ing7: 'Kaffir lime leaf powder',
    amount7: '0.125 tsp',
    ing8: 'Fresh cilantro',
    amount8: 'some',
    ing9: 'Thai basil',
    amount9: 'some',
    ing10: 'ground chipotle',
    amount10: '1 tbsp',
    ing11: 'dried guajillo chillies',
    amount11: '2',
    ing12: 'lemongrass stalk',
    amount12: '1',
    ing13: 'shallots',
    amount13: '0.5 cup',
    ing14: 'Thai shrimp paste',
    amount14: '1 tbsp',
    ing15: '',
    amount15: '',
    step1: 'In a mini blender or food processor, blend chiles and salt until pulverized. Add lemongrasss, ginger, galangal, turmeric, chopped shallots, garlic, shrimp paste one by one in order listed, fully pulverizing each before adding the next.',
    step2: 'Combine curry paste, beef, soy sauce, and ground chipotle in a pot; stir to evenly coat beef. Add coconut oil and cook, stirring occasionally, over medium heat for 5 minutes. Add broth and bring to a boil. Cover, reduce heat to medium-low, and simmer, stirring occasionally, until beef is tender but not falling apart, 2-2 1/2 hours.',
    step3: '30 minutes before stew is done, stir in the turnip.',
    step4: '5 minutes before stew is done, add the halved shallots.',
    step5: 'Garnish with cilantro and basil.',
    step6: '',
    step7: '',
    step8: '',
    step9: '',
    step10: ''
  }
];
