# Generated by Django 3.1.7 on 2021-04-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210429_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing1', models.CharField(max_length=300)),
                ('amount1', models.CharField(max_length=300)),
                ('ing2', models.CharField(max_length=300)),
                ('amount2', models.CharField(max_length=300)),
                ('ing3', models.CharField(max_length=300)),
                ('amount3', models.CharField(max_length=300)),
                ('ing4', models.CharField(max_length=300)),
                ('amount4', models.CharField(max_length=300)),
                ('ing5', models.CharField(max_length=300)),
                ('amount5', models.CharField(max_length=300)),
                ('ing6', models.CharField(max_length=300)),
                ('amount6', models.CharField(max_length=300)),
                ('ing7', models.CharField(max_length=300)),
                ('amount7', models.CharField(max_length=300)),
                ('ing8', models.CharField(max_length=300)),
                ('amount8', models.CharField(max_length=300)),
                ('step1', models.TextField(max_length=1000)),
                ('step2', models.TextField(max_length=1000)),
                ('step3', models.TextField(max_length=1000)),
                ('step4', models.TextField(max_length=1000)),
                ('step5', models.TextField(max_length=1000)),
                ('step6', models.TextField(max_length=1000)),
                ('step7', models.TextField(max_length=1000)),
                ('step8', models.TextField(max_length=1000)),
                ('step9', models.TextField(max_length=1000)),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ingredients', to='recipes.recipes')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('id',),
            },
        ),
    ]
