# Generated by Django 3.1.7 on 2021-04-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
    ]
