# Generated by Django 3.1.7 on 2021-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='amount1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount6',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount8',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing6',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ing8',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step1',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step2',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step3',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step4',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step5',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step6',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step7',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step8',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='step9',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
